
build: 
	nasm -f elf p5.asm
	ld -m elf_i386 p5.o -o ../../bin/practica5.exe ../../lib/libpc_io.a

build2:
	nasm -f elf p5.asm
	ld -m elf_i386 p5a.o -o ../../bin/practica5.exe ../../lib/libpc_io.a

run:
	./../../bin/practica5.exe